# Generated by Django 4.2.16 on 2024-11-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_carrera_user_phone_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='carrera',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
