# Generated by Django 4.2.16 on 2024-11-21 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_carrera'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='telefono',
        ),
    ]
