# Generated by Django 4.2.15 on 2024-10-06 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ensayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ensayo', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_ensayo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_ensayo', models.DateTimeField(verbose_name='Fecha Ensayo')),
                ('estado_ensayo', models.CharField(blank=True, default='Activa', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Ensayo',
                'verbose_name_plural': 'Ensayos',
                'ordering': ['codigo_ensayo', 'nombre_ensayo', 'fecha_ensayo', 'estado_ensayo'],
            },
        ),
        migrations.CreateModel(
            name='Resultado_ensayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.IntegerField(blank=True, null=True)),
                ('fuerza', models.DecimalField(blank=True, decimal_places=6, max_digits=200, null=True)),
                ('time_of_fly', models.DecimalField(blank=True, decimal_places=6, max_digits=200, null=True)),
                ('esd', models.DecimalField(blank=True, decimal_places=6, max_digits=200, null=True)),
                ('strain', models.DecimalField(blank=True, decimal_places=6, max_digits=200, null=True)),
                ('stress', models.IntegerField(blank=True, null=True)),
                ('ensayo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensayo.ensayo')),
            ],
            options={
                'verbose_name': 'Resultado_ensayo',
                'verbose_name_plural': 'Resultado_ensayos',
                'ordering': [],
            },
        ),
    ]
