# Generated by Django 4.2.15 on 2024-10-09 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ensayo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultado_ensayo',
            options={'ordering': ['tiempo', 'fuerza', 'time_of_fly', 'esd', 'strain', 'stress'], 'verbose_name': 'Resultado_ensayo', 'verbose_name_plural': 'Resultado_ensayos'},
        ),
        migrations.CreateModel(
            name='Ensayo_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocidad_ensayo', models.IntegerField(blank=True, null=True)),
                ('ensayo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensayo.ensayo')),
            ],
            options={
                'verbose_name': 'Ensayo_detalle',
                'verbose_name_plural': 'Ensayo_detalles',
                'ordering': ['velocidad_ensayo'],
            },
        ),
    ]
