# Generated by Django 4.1.13 on 2024-10-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayo', '0002_alter_resultado_ensayo_options_ensayo_detalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultado_ensayo',
            name='ensayo',
        ),
        migrations.AlterModelOptions(
            name='ensayo',
            options={'ordering': ['codigo_ensayo', 'nombre_ensayo', 'fecha_ensayo', 'estado_ensayo', 'tiempo', 'fuerza', 'time_of_fly', 'esd', 'strain', 'stress'], 'verbose_name': 'Ensayo', 'verbose_name_plural': 'Ensayos'},
        ),
        migrations.AddField(
            model_name='ensayo',
            name='esd',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=200, null=True),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='espesor',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=200, null=True),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='fuerza',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=200, null=True),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='strain',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=200, null=True),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='stress',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='tiempo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='time_of_fly',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=200, null=True),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='velocidad_ensayo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Ensayo_detalle',
        ),
        migrations.DeleteModel(
            name='Resultado_ensayo',
        ),
    ]
