# Generated by Django 4.2 on 2024-10-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensayo', '0003_remove_resultado_ensayo_ensayo_alter_ensayo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ensayo',
            options={'ordering': ['codigo_ensayo', 'nombre_ensayo', 'fecha_ensayo', 'estado_ensayo', 'tiempo', 'fuerza', 'espesor', 'time_of_fly', 'esd', 'strain', 'stress'], 'verbose_name': 'Ensayo', 'verbose_name_plural': 'Ensayos'},
        ),
    ]
