# Generated by Django 2.0.2 on 2024-10-25 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensayo', '0004_alter_ensayo_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ensayo',
        ),
    ]
